### ISSUE TITLE
网易云音乐软件长宽比例较长时专辑封面会非方形而强行切割专辑封面

### ISSUE THREAD

**Issue by sSkieri** [BetterNCM/ArkTheme#2]
![QQ_Image_1676291721148](https://user-images.githubusercontent.com/81229545/218459116-8eeb2d98-366e-498d-9b67-332ae67bf6cd.jpg)
 同样歌单页面的分享菜单也会比例失调导致效果有点不尽人意  同时建议增加底部底栏的圆角比例的修改 主题很好看 很喜欢

**Comment by std-microblock** [comment]
![image](https://user-images.githubusercontent.com/66859419/221229769-0bea075e-df49-4e59-8c4a-6e8cc2773cd1.png)

![image](https://user-images.githubusercontent.com/66859419/221229906-7836eefe-c5b8-411f-907f-4ad3f317e77a.png)

2. 是指什么

**Comment by sSkieri** [comment]
抱歉没有表达清晰233 
2.是指在歌单页面 歌单名称下面的“播放全部 收藏 分享”那三个选项部分的比例会和之前的歌曲封面一样被强制拉伸变大
而3.则是希望增加这一部分的圆角弧度的调整  
![QQ_Image_1677303744027](https://user-images.githubusercontent.com/81229545/221340678-6b7707bf-cac6-4cee-beaa-ce16f33043c4.jpg)

**Comment by std-microblock** [comment]
![image](https://user-images.githubusercontent.com/66859419/221357614-53feeedf-05f9-4dc3-94ea-8c99cee032a7.png)

啊？


1. 3. 已添加选项
